### ISSUE TITLE
Should support nested schemas

### ISSUE THREAD

**Issue by simonguest** [simonguest/swagger-mongoose#1]
Current version only supports flat schemas. Future request would be to support nested schemas.

**Comment by semisay** [comment]
Hello Simon!

Any updates regarding this issue?

**Comment by simonguest** [comment]
Hi Semisay - just saw that you issued a PR, but seemed to close it before I could test/commit. Do you want to go ahead and resubmit or are you still working on it?  Thanks.

**Comment by Leyart** [comment]
Any update on nested schemas?

**Comment by simonguest** [comment]
I have a submitted PR, but haven't had time to test it (or to write a test). You are welcome to take a look if you'd like however.

**Comment by Leyart** [comment]
That's great. I will at least test it (even though I will probably don't have time to write tests). I am using it along with a modified version of https://github.com/krakenjs/generator-swaggerize. 
If there was a simple way to integrate swagger-mongoose into it, then I could even write the test case.
Do you have any advice on the matter?

Best,
Luca

**Comment by simonguest** [comment]
Functionality now added. 27d4b2191dbec707ac00265fe3ca5e4538841337
