### ISSUE TITLE
should support models composition by `allOf`

### ISSUE THREAD

**Issue by AilisObrian** [simonguest/swagger-mongoose#20]
According to [swagger 2.0 spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#models-with-composition), models with composition would be handled by 'allOf:'.

``` yaml
paths:
  /test:
    summary: "Test Model 1 and 2"
    responses:
      "200":
        description: "Model 1 and 2"
        schema:
          $ref: "#/definitions/Model3"
definitions:
  Model1:
    description: "Model 1"
    properties:
      firstName:
        type: string
  Model2:
    description: "Model 2"
    properties:
      lastName:
        type: string
  Model3:
    description: "Model 1 and 2"
    allOf:
      - $ref: "#/definitions/Model1"
      - $ref: "#/definitions/Model2"
    x-swagger-mongoose:
      exclude-schema: true
```

I tried with above definitions:
- [Sway (Swagger Validator)](https://github.com/apigee-127/sway) passed,
- [swagger-ui](https://github.com/swagger-api/swagger-ui) displayed well,
- but swagger-mongoose(latest) crashed with `Error: Unrecognized schema type: undefined` at `allOf` lines

So,
- we should support `allOf`.
- and ignore models with `exclude-schema: true` just before when `getSchema()`.

``` javascript
      if (definition[customMongooseProperty]) {
        processMongooseDefinition(key, definition[customMongooseProperty]);
      }
      if (excludeSchema[key]) {  // <-- here!
        return;
      }
      object = getSchema(key, definition);
```

Please advise me. Thanks all.

**Comment by briananderson1222** [comment]
@AilisObrian feel free to include a PR for this as well. I hadn't run into the `allOf` use case yet but this seems reasonable

**Comment by AilisObrian** [comment]
@briananderson1222 Thanks for leading this. PR created.

**Comment by AilisObrian** [comment]
merged #25

**Comment by cspeer** [comment]
I'm a little confused here because `allOf` does not work even though this issue is closed. Am I missing something? Thanks :)

**Comment by AilisObrian** [comment]
@cspeer Oh, with this patch, we can compose models by `allOf` just for the swagger expression.
But not create the composed model to Mongoose/MongoDB.

**Comment by cspeer** [comment]
Oh I see. Bummer. Thanks for the reply :)
