### ISSUE TITLE
npm hosts old version

### ISSUE THREAD

**Issue by towertop** [simonguest/swagger-mongoose#23]
I fall into this problem that 'npm install swagger-mongoose' gets code different from mater branch.

And it turn out that npm is still hosting version 0.1.3 while README.md is description the latest 1.1.0 .

I changed to install from github directly:
`npm install -S git+https://github.com/simonguest/swagger-mongoose.git`

But this confusion should have been avoided. Please consider to:
- Update the npm module at https://www.npmjs.com/package/swagger-mongoose
- Hint about the correct way to get this awesome library

Thanks.

**Comment by briananderson1222** [comment]
@paul42 I believe your temporary package.json changes made their way into master. @simonguest after updating the package json would you mind doing an npm publish?

**Comment by simonguest** [comment]
I noticed that the package.json file name has been changed to "swagger-mongoose-fork". I'll update to reflect the acutal package name, but the version to 1.1.1 to avoid confusion, and npm publish.

**Comment by paul42** [comment]
Thanks for handling this @simonguest, I apologize everyone, in my haste to scratch my itch I got a bit sloppy, so sorry for that!

**Comment by simonguest** [comment]
No worries, @paul42  - Now fixed. 1.1.2 now published to npm.
