### ISSUE TITLE
Abnormal behavior caused by mongo/mongoose version mismatch

### ISSUE THREAD

**Issue by nakamorichi** [simonguest/swagger-mongoose#33]
Problem
======
Swagger definition file not sometimes not compiled correctly when parent project and swagger-mongoose use different versions of mongodb and/or mongoose.

Solution
======
mongodb and mongoose should be set as peer dependencies in order to have Mongoose models that are compatible with the Mongoose version of the parent application.

See https://github.com/Kitanotori/swagger-mongoose/commit/f77d01947582362a490268dbf9dd4bb1febb11d5

EDIT: never mind, the problem was actually caused by `npm link`inking swagger-mongoose to my project, which somehow messed up Mongoose.

**Comment by briananderson1222** [comment]
@Kitanotori Is this still an issue?

**Comment by briananderson1222** [comment]
Should be fixed by https://github.com/simonguest/swagger-mongoose/pull/35
